wallpaper {
    monitor = DP-2
    path = ~/.resources/wallpapers/dracula_arch.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.resources/wallpapers/dracula_arch.png
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/.resources/wallpapers/dracula_arch.png
    fit_mode = cover
}
